import { useMemo, useState } from "react";
import TopBar from "../../components/TopBar";
import Badge from "../../components/Badge";
import { useApi } from "../../hooks/useApi";
import { mdmApi } from "../../api/client";
import { LoadingState, ErrorState, EmptyState } from "../../components/StateMessages";
import type { MdmRecord } from "../../types";

function qualityTone(score: number) {
  if (score >= 80) return "success";
  if (score >= 55) return "warning";
  return "danger";
}

function RecordRow({ record }: { record: MdmRecord }) {
  const [expanded, setExpanded] = useState(false);
  const [suggestions, setSuggestions] = useState<string[] | null>(null);
  const [source, setSource] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  async function loadSuggestions() {
    if (suggestions) return;
    setLoading(true);
    const result = await mdmApi.aiCleansingSuggestions(record.id);
    setSuggestions(result.suggestions);
    setSource(result.source);
    setLoading(false);
  }

  return (
    <>
      <tr className="clickable" onClick={() => { setExpanded(!expanded); if (!expanded) loadSuggestions(); }}>
        <td><strong>{record.attributes.name || record.id}</strong></td>
        <td>{record.entityType}</td>
        <td>
          <span className={`badge badge-${qualityTone(record.qualityScore || 0)}`}>{record.qualityScore}%</span>
        </td>
        <td>{(record.issues || []).map((i) => <Badge key={i} tone="warning">{i}</Badge>)}</td>
        <td>{expanded ? "▲" : "▼"}</td>
      </tr>
      {expanded && (
        <tr>
          <td colSpan={5} style={{ background: "var(--surface-alt)" }}>
            <div style={{ padding: "10px 4px" }}>
              <table className="data-table" style={{ marginBottom: 10 }}>
                <tbody>
                  {Object.entries(record.attributes).map(([k, v]) => (
                    <tr key={k}>
                      <td style={{ width: 140, fontWeight: 600 }}>{k}</td>
                      <td>{v === null || v === "" ? <em style={{ color: "var(--danger)" }}>missing</em> : String(v)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="ai-insight-box">
                <strong>✦ AI Cleansing Suggestions</strong>
                {loading && <div>Loading…</div>}
                {suggestions && (
                  <ul style={{ margin: "8px 0 0", paddingLeft: 18 }}>
                    {suggestions.map((s, i) => <li key={i}>{s}</li>)}
                  </ul>
                )}
                {source && (
                  <div style={{ fontSize: 11, color: "var(--text-faint)", marginTop: 6, textTransform: "uppercase" }}>
                    {source === "claude-opus-5" ? "Generated by Claude Opus 5" : "Rule-based fallback"}
                  </div>
                )}
              </div>
            </div>
          </td>
        </tr>
      )}
    </>
  );
}

export default function RecordsPage() {
  const { data, loading, error } = useApi(() => mdmApi.listRecords(), []);
  const [entityType, setEntityType] = useState("");
  const [issueFilter, setIssueFilter] = useState("");

  const filtered = useMemo(() => {
    if (!data) return [];
    return data.filter((r) => {
      const matchesType = !entityType || r.entityType === entityType;
      const matchesIssue = !issueFilter || (r.issues || []).includes(issueFilter);
      return matchesType && matchesIssue;
    });
  }, [data, entityType, issueFilter]);

  return (
    <>
      <TopBar title="Master Records" subtitle="MDM · Profiling &amp; Quality" />
      <div className="content">
        <div className="filter-bar">
          <select value={entityType} onChange={(e) => setEntityType(e.target.value)}>
            <option value="">All entity types</option>
            <option value="Customer">Customer</option>
            <option value="Supplier">Supplier</option>
            <option value="Product">Product</option>
          </select>
          <select value={issueFilter} onChange={(e) => setIssueFilter(e.target.value)}>
            <option value="">All issues</option>
            <option value="DUPLICATE">Duplicate</option>
            <option value="INCOMPLETE">Incomplete</option>
            <option value="CONFLICT">Conflict</option>
            <option value="FORMAT">Format</option>
          </select>
        </div>

        {loading && <LoadingState />}
        {error && <ErrorState message={error} />}
        {data && filtered.length === 0 && <EmptyState message="No records match your filters." />}

        {filtered.length > 0 && (
          <div className="card">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Record</th>
                  <th>Entity Type</th>
                  <th>Quality Score</th>
                  <th>Issues</th>
                  <th />
                </tr>
              </thead>
              <tbody>
                {filtered.map((r) => (
                  <RecordRow key={r.id} record={r} />
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </>
  );
}
