import { useParams, Link } from "react-router-dom";
import TopBar from "../../components/TopBar";
import Badge from "../../components/Badge";
import StatCard from "../../components/StatCard";
import { useApi } from "../../hooks/useApi";
import { crmApi } from "../../api/client";
import { LoadingState, ErrorState } from "../../components/StateMessages";

export default function Customer360Page() {
  const { id } = useParams<{ id: string }>();
  const { data, loading, error } = useApi(() => crmApi.customer360(id!), [id]);

  if (loading) return <div className="content"><LoadingState /></div>;
  if (error || !data) return <div className="content"><ErrorState message={error || "Not found"} /></div>;

  const { account, contacts, openOpportunities, wonOpportunities, pipelineValue, wonValue, openActivitiesCount, recentActivities, aiInsight, aiInsightSource } = data;

  return (
    <>
      <TopBar title={account.accountName} subtitle={`CRM · Customer 360 · ${account.industry}`} />
      <div className="content">
        <div className="grid grid-4 section">
          <StatCard label="Account Manager" value={account.accountManager} />
          <StatCard label="Open Opportunities" value={openOpportunities.length} hint={`$${pipelineValue.toLocaleString()} pipeline`} />
          <StatCard label="Won Business" value={`$${wonValue.toLocaleString()}`} />
          <StatCard label="Customer Health" value={account.customerStatus} />
        </div>

        <div className="ai-panel section">
          <div className="ai-panel-header">
            <span className="spark">✦</span>
            AI Insight
          </div>
          <div className="ai-insight-box">{aiInsight}</div>
          <span className="source-tag">
            {aiInsightSource === "claude-opus-5" ? "Generated by Claude Opus 5" : "Generated by rule-based fallback"}
          </span>
        </div>

        <div className="grid grid-2 section">
          <div className="card">
            <div className="card-header">
              <h3>Account Details</h3>
            </div>
            <table className="data-table">
              <tbody>
                <tr><td>Region</td><td>{account.region}</td></tr>
                <tr><td>Country</td><td>{account.country}</td></tr>
                <tr><td>Revenue</td><td>${account.revenue.toLocaleString()}</td></tr>
                <tr><td>Employees</td><td>{account.employees.toLocaleString()}</td></tr>
                <tr><td>Segment</td><td>{account.customerSegment}</td></tr>
                <tr><td>Open Activities</td><td>{openActivitiesCount}</td></tr>
              </tbody>
            </table>
          </div>

          <div className="card">
            <div className="card-header">
              <h3>Contacts</h3>
            </div>
            {contacts.length === 0 && <p style={{ color: "var(--text-muted)" }}>No contacts on file.</p>}
            {contacts.map((c) => (
              <div key={c.id} style={{ padding: "8px 0", borderBottom: "1px solid var(--border)" }}>
                <strong>{c.firstName} {c.lastName}</strong> {c.decisionMaker && <Badge tone="success">Decision Maker</Badge>}
                <div style={{ fontSize: 12.5, color: "var(--text-muted)" }}>{c.jobTitle} · {c.email}</div>
              </div>
            ))}
          </div>
        </div>

        <div className="card section">
          <div className="card-header">
            <h3>Open Opportunities</h3>
          </div>
          {openOpportunities.length === 0 && <p style={{ color: "var(--text-muted)" }}>No open opportunities.</p>}
          {openOpportunities.length > 0 && (
            <table className="data-table">
              <thead>
                <tr><th>Opportunity</th><th>Stage</th><th>Value</th><th>Probability</th><th>Close Date</th></tr>
              </thead>
              <tbody>
                {openOpportunities.map((o) => (
                  <tr key={o.id}>
                    <td><Link to={`/crm/opportunities/${o.id}`}>{o.opportunityName}</Link></td>
                    <td><Badge>{o.stage}</Badge></td>
                    <td>${o.estimatedValue.toLocaleString()}</td>
                    <td>{o.probability}%</td>
                    <td>{new Date(o.expectedCloseDate).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>

        {wonOpportunities.length > 0 && (
          <div className="card section">
            <div className="card-header">
              <h3>Won Business</h3>
            </div>
            <table className="data-table">
              <thead><tr><th>Opportunity</th><th>Value</th><th>Closed</th></tr></thead>
              <tbody>
                {wonOpportunities.map((o) => (
                  <tr key={o.id}>
                    <td>{o.opportunityName}</td>
                    <td>${o.estimatedValue.toLocaleString()}</td>
                    <td>{new Date(o.expectedCloseDate).toLocaleDateString()}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        <div className="card section">
          <div className="card-header">
            <h3>Recent Activity Timeline</h3>
          </div>
          {recentActivities.length === 0 && <p style={{ color: "var(--text-muted)" }}>No recent activity.</p>}
          <ul className="timeline">
            {recentActivities.map((a) => (
              <li key={a.id}>
                <div className="timeline-date">{new Date(a.activityDate).toLocaleDateString()} · {a.activityType}</div>
                <div className="timeline-title">{a.subject}</div>
                <div className="timeline-desc">{a.description}</div>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
}
